on:
  push:
    branches:
      - main

name: Deploy to heroku

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
#CAMBIAR AQUI NOMBRE DEL APLICATIVO EN HEROKU EN EL DASHBOARD
  HEROKU_APP_NAME: ${{ 'app-netcore-prograone' }}

jobs:
  build_webapp:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Docker build
      run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

    - name: Publish
      run: |
        heroku container:push web -a $HEROKU_APP_NAME
        heroku container:release web -a $HEROKU_APP_NAME